# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Septagon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; Maksim Sundukov 2016 | All Rights Reserved.<br>Like somebody wants to copy that site. In fact, I don’t even need the notice to claim copyright; the law eliminated the requirement of public notice in 1989.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://e-xor.github.io" # the base hostname & protocol for your site
github_username:  E-Xor

# Build settings
markdown: kramdown
